
[colors.primary]
background = "#282828"
foreground = "#dfbf8e"

[colors.normal]
black = "#665c54"
red = "#ea6962"
green = "#a9b665"
yellow = "#e78a4e"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#dfbf8e"

[colors.bright]
black = "#928374"
red = "#ea6962"
green = "#a9b665"
yellow = "#e3a84e"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#dfbf8e"

[general]
import = [
  "/home/penguineo/.local/share/pnpm/global/5/.pnpm/alacritty-themes@6.0.2/node_modules/alacritty-themes/themes/Gruvbox-Dark.toml"
]
[window]
dynamic_title = false
